import type { Tour } from './types';
import { img } from './images';

/**
 * Seed tour catalogue. Content is original and rewritten from competitor
 * research (never copied). The structure scales to hundreds of tours — add
 * records here or swap this module for a CMS query with the same shape.
 */

const STANDARD_CANCELLATION =
  'Free cancellation up to 24 hours before your tour start time for a full refund. Cancellations within 24 hours are non-refundable. If we cancel due to weather or safety, you receive a full refund or a free reschedule.';

const SUN_ESSENTIALS = ['Reef-safe sunscreen (SPF 30+)', 'Sunglasses and a hat', 'A light cover-up or towel'];

export const tours: Tour[] = [
  {
    slug: 'marsa-alam-desert-safari',
    title: 'Marsa Alam Desert Safari with Quad, Camel & Bedouin Dinner',
    seoTitle: 'Marsa Alam Desert Safari 2026 | Quad, Camel & Bedouin Dinner',
    metaDescription:
      'The ultimate Marsa Alam desert safari: quad biking, a camel ride, a Bedouin village and a sunset dinner under the stars. Licensed guides & free hotel pickup.',
    summary:
      'Quad biking, camel riding, a Bedouin village and a starlit dinner — the complete Eastern Desert evening from Marsa Alam.',
    overview: [
      'Trade the beach for the silence of the Eastern Desert on our signature Marsa Alam safari. In a single unforgettable evening you’ll ride a quad bike across open dunes, meet the Ababda Bedouin who call this desert home, climb aboard a camel as the light turns gold, and finish with a barbecue dinner beneath one of the darkest, star-filled skies in Egypt.',
      'Every departure travels with licensed local guides and a support vehicle, so first-time riders and families feel completely at ease. This is the desert done properly: unhurried, authentic and safe.',
    ],
    category: 'desert-safari',
    tags: ['quad-bike', 'camel-ride', 'bedouin', 'sunset', 'family-friendly'],
    destinationSlugs: ['wadi-el-gemal'],
    price: { amount: 35, currency: 'EUR', compareAt: 45, unit: 'per person', childAmount: 20 },
    durationHours: 6,
    durationLabel: 'Half day (5–6 hrs, afternoon)',
    difficulty: 'Easy',
    groupSize: '1–20 people',
    languages: ['English', 'German', 'Italian', 'Arabic'],
    availability: 'Daily',
    minAge: 3,
    heroImage: img('1509316785289-025f5b846b35', 'Quad bikes lined up on golden dunes for a Marsa Alam desert safari at sunset', { priority: true }),
    gallery: [
      img('1451337516015-6b6e9a44a8a3', 'Rider on a quad bike kicking up sand in the Marsa Alam desert'),
      img('1547234935-80c7145ec969', 'Camels resting on a dune ridge during a Marsa Alam sunset safari'),
      img('1518709268805-4e9042af9f23', 'Bedouin tent with cushions and lanterns set for dinner in the Eastern Desert'),
      img('1470071459604-3b5ec3a7fe05', 'Star-filled night sky over the Marsa Alam desert camp'),
    ],
    highlights: [
      'Quad bike across open desert with a guided convoy',
      'Ride a camel along the dune ridge at golden hour',
      'Visit an authentic Ababda Bedouin village',
      'Barbecue dinner and sweet tea under the stars',
      'Traditional music and a stargazing session',
    ],
    included: [
      'Air-conditioned hotel pickup and drop-off',
      'Quad bike with fuel and safety briefing',
      'Camel ride',
      'Bedouin village visit with tea',
      'Barbecue dinner (vegetarian option available)',
      'Licensed local guide',
      'Bottled water',
    ],
    excluded: ['Gratuities (optional)', 'Personal expenses', 'Private quad bike upgrade'],
    whatToBring: [...SUN_ESSENTIALS, 'Closed shoes', 'A scarf for dust', 'A light jacket for the evening', 'Your camera'],
    itinerary: [
      { time: '2:30 PM', title: 'Hotel pickup', description: 'Our driver collects you from your Marsa Alam or Port Ghalib hotel in an air-conditioned vehicle.' },
      { time: '3:30 PM', title: 'Safety briefing & quad ride', description: 'Meet your guides, gear up, and set off across the dunes on your quad bike in a supervised convoy.' },
      { time: '4:45 PM', title: 'Bedouin village', description: 'Stop at an Ababda village to see traditional desert life and share a glass of Bedouin tea.' },
      { time: '5:30 PM', title: 'Camel ride & sunset', description: 'Climb aboard a camel and ride the ridge as the sun sets behind the Red Sea Hills.' },
      { time: '6:30 PM', title: 'Dinner under the stars', description: 'Enjoy a barbecue dinner, live music and a guided look at the desert night sky.' },
      { time: '8:30 PM', title: 'Return', description: 'Relax on the drive back to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'El Quseir (surcharge)', 'Coraya Bay', 'Sharm El Luli hotels'],
      note: 'Pickup times are confirmed by WhatsApp the evening before. Please be ready in your hotel lobby 10 minutes early.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Do I need a driving licence to ride a quad bike?', answer: 'No licence is required. You’ll get a full safety briefing and practice run, and our guides ride alongside you the whole way. The route is chosen for beginners.' },
      { question: 'Is the desert safari suitable for children?', answer: 'Yes. Children aged 3+ are welcome and ride as passengers on a guide’s quad or in the support vehicle. Under-16s cannot drive a quad alone but love the camels and the camp.' },
      { question: 'What time does the safari start?', answer: 'The afternoon safari is timed to catch sunset, so pickups are usually between 2:00 and 3:00 PM depending on your hotel. Exact times are confirmed the day before.' },
      { question: 'Is it safe?', answer: 'Very. We travel in a guided convoy with a support 4x4, first-aid kit and experienced local guides. Speeds are kept sensible and helmets are provided.' },
      { question: 'What should I wear?', answer: 'Closed shoes, comfortable clothes you don’t mind getting dusty, and a light jacket for the evening — desert temperatures drop quickly after sunset.' },
      { question: 'Can you cater for vegetarians or allergies?', answer: 'Yes. Vegetarian dinners are always available, and we can accommodate most dietary needs with advance notice when you book.' },
      { question: 'Will there be a lot of dust?', answer: 'Some, yes — it’s the desert. A scarf or buff over your mouth and sunglasses keep it comfortable. We space the convoy to reduce dust for riders behind.' },
      { question: 'How long is the quad ride?', answer: 'Around 45 minutes to an hour of actual riding, split into segments with stops, so it never feels rushed or tiring.' },
      { question: 'Do you offer hotel pickup?', answer: 'Yes, round-trip air-conditioned hotel transfers from Marsa Alam and Port Ghalib are included. Pickups from farther hotels may carry a small surcharge.' },
      { question: 'Can I book for a large group or private event?', answer: 'Absolutely. Message us on WhatsApp for private group rates, honeymoon set-ups and special occasions.' },
    ],
    relatedTours: ['quad-bike-marsa-alam', 'camel-ride-marsa-alam', 'super-safari-jeep-adventure'],
    rating: 4.9,
    reviewCount: 612,
    featured: true,
    bestseller: true,
    updatedAt: '2026-06-01',
  },
  {
    slug: 'quad-bike-marsa-alam',
    title: 'Quad Bike Marsa Alam: Sunset Desert Adventure',
    seoTitle: 'Quad Bike Marsa Alam | Sunset Desert Adventure & Hotel Pickup',
    metaDescription:
      'Ride a quad bike across the Marsa Alam desert on a guided sunset adventure. Beginner-friendly, licensed guides, safety gear and free hotel pickup included.',
    summary: 'A focused, adrenaline-friendly quad biking trip across open desert, timed for a spectacular Red Sea sunset.',
    overview: [
      'For travellers who want the thrill without the full-day commitment, our quad bike adventure delivers pure desert fun in a compact afternoon. You’ll master your machine in minutes, then follow your guide across rolling dunes and dry valleys to a sunset viewpoint over the Red Sea Hills.',
      'It’s beginner-friendly by design — no licence, no experience, just a helmet, a briefing and a grin. Bedouin tea and a photo stop round out the ride before you’re back at your hotel for dinner.',
    ],
    category: 'desert-safari',
    tags: ['quad-bike', 'sunset', 'adventure', 'short-trip'],
    destinationSlugs: ['wadi-el-gemal'],
    price: { amount: 25, currency: 'EUR', compareAt: 32, unit: 'per person' },
    durationHours: 3,
    durationLabel: 'Short trip (3 hrs)',
    difficulty: 'Easy',
    groupSize: '1–15 people',
    languages: ['English', 'German', 'Italian'],
    availability: 'Daily',
    minAge: 8,
    heroImage: img('1451337516015-6b6e9a44a8a3', 'Quad bike rider speeding across the Marsa Alam desert at golden hour', { priority: true }),
    gallery: [
      img('1509316785289-025f5b846b35', 'Line of quad bikes on a dune ridge in Marsa Alam'),
      img('1547234935-80c7145ec969', 'Desert mountains glowing orange at sunset near Marsa Alam'),
      img('1518709268805-4e9042af9f23', 'Bedouin tea stop during a quad bike tour in the Eastern Desert'),
    ],
    highlights: [
      'Guided quad ride across open dunes and valleys',
      'Sunset viewpoint over the Red Sea Hills',
      'Full safety briefing and helmet provided',
      'Bedouin tea and photo stop',
      'No licence or experience needed',
    ],
    included: ['Hotel pickup and drop-off', 'Quad bike, fuel and helmet', 'Safety briefing', 'Bedouin tea', 'Local guide', 'Bottled water'],
    excluded: ['Dinner', 'Gratuities', 'Private/solo quad upgrade for under-16s'],
    whatToBring: [...SUN_ESSENTIALS, 'Closed shoes', 'A buff or scarf for dust'],
    itinerary: [
      { time: '3:30 PM', title: 'Pickup & briefing', description: 'Collected from your hotel, then a hands-on safety briefing and practice loop.' },
      { time: '4:15 PM', title: 'Desert ride', description: 'Follow your guide across dunes and dry riverbeds toward the sunset viewpoint.' },
      { time: '5:15 PM', title: 'Sunset & tea', description: 'Pause for photos and Bedouin tea as the sun sinks behind the mountains.' },
      { time: '6:00 PM', title: 'Return', description: 'Ride back and transfer to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'Madinat Coraya'],
      note: 'Pickup roughly 30 minutes before ride time; confirmed by WhatsApp the day before.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Do I need experience to ride a quad bike?', answer: 'None at all. Most guests have never ridden before. The briefing and practice loop get you confident in minutes, and your guide sets a comfortable pace.' },
      { question: 'What is the minimum age to drive a quad?', answer: 'Riders aged 16+ can drive their own quad. Children 8–15 ride as passengers with a guide. Younger children are better suited to our full desert safari.' },
      { question: 'Can two people share one quad?', answer: 'Yes, a double quad option is available so a child or partner can ride pillion with an adult. Let us know when booking.' },
      { question: 'Is a helmet provided?', answer: 'Yes, helmets are included and mandatory. We also provide a dust scarf on request.' },
      { question: 'How fast do the quads go?', answer: 'The quads are capable of higher speeds, but on this guided route we keep a safe, comfortable pace suited to the whole group.' },
      { question: 'What happens if the weather is bad?', answer: 'Sandstorms or unsafe conditions are rare, but if they occur we reschedule or refund you in full.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip transfers from Marsa Alam and Port Ghalib are included in the price.' },
      { question: 'Should I bring my phone or camera?', answer: 'Yes — there are great photo moments at the sunset stop. Bring a strap or zip pocket so nothing is lost on the ride.' },
      { question: 'Can I combine this with a camel ride or dinner?', answer: 'Yes — our full Marsa Alam Desert Safari adds a camel ride, Bedouin dinner and stargazing. Ask us to upgrade.' },
      { question: 'Is it dusty?', answer: 'A little, as with any desert ride. Sunglasses and a scarf keep it comfortable, and we stagger the convoy to reduce dust.' },
    ],
    relatedTours: ['marsa-alam-desert-safari', 'camel-ride-marsa-alam', 'super-safari-jeep-adventure'],
    rating: 4.8,
    reviewCount: 421,
    featured: true,
    bestseller: true,
    updatedAt: '2026-06-05',
  },
  {
    slug: 'camel-ride-marsa-alam',
    title: 'Camel Ride Marsa Alam: Sunset Desert Experience',
    seoTitle: 'Camel Ride Marsa Alam | Sunset Desert Experience & Bedouin Tea',
    metaDescription:
      'A gentle sunset camel ride through the Marsa Alam desert with Bedouin guides, tea and Red Sea Hills views. Relaxed, family-friendly, hotel pickup included.',
    summary: 'A relaxed, romantic camel trek along the dune ridges at sunset, with Bedouin tea and mountain views.',
    overview: [
      'Some journeys are meant to be slow. Our sunset camel ride carries you at the desert’s own pace, swaying along the dune ridges as the light softens and the Red Sea Hills turn rose and gold.',
      'Led by Ababda handlers who have raised camels for generations, this is the gentlest way to feel the desert — perfect for families, couples and anyone who’d rather savour the scenery than chase adrenaline. Sweet Bedouin tea and a photo stop complete the evening.',
    ],
    category: 'desert-safari',
    tags: ['camel-ride', 'sunset', 'romantic', 'family-friendly', 'relaxed'],
    destinationSlugs: ['wadi-el-gemal'],
    price: { amount: 20, currency: 'EUR', unit: 'per person', childAmount: 12 },
    durationHours: 3,
    durationLabel: 'Short trip (2.5–3 hrs)',
    difficulty: 'Easy',
    groupSize: '1–20 people',
    languages: ['English', 'German', 'Italian', 'Arabic'],
    availability: 'Daily',
    minAge: 3,
    heroImage: img('1547234935-80c7145ec969', 'Camel caravan silhouetted against a Marsa Alam desert sunset', { priority: true }),
    gallery: [
      img('1518709268805-4e9042af9f23', 'Bedouin camp with cushions and a fire in the Marsa Alam desert'),
      img('1509316785289-025f5b846b35', 'Golden dunes stretching toward the Red Sea Hills at dusk'),
      img('1470071459604-3b5ec3a7fe05', 'Stars beginning to appear over a desert camel camp near Marsa Alam'),
    ],
    highlights: [
      'Gentle guided camel trek along the dune ridge',
      'Golden-hour views over the Red Sea Hills',
      'Traditional Ababda Bedouin handlers',
      'Bedouin tea and a relaxed photo stop',
      'Ideal for families, couples and all ages',
    ],
    included: ['Hotel pickup and drop-off', 'Camel ride with handler', 'Bedouin tea', 'Local guide', 'Bottled water'],
    excluded: ['Dinner', 'Gratuities', 'Souvenir photos'],
    whatToBring: [...SUN_ESSENTIALS, 'Comfortable trousers', 'A light jacket for after sunset'],
    itinerary: [
      { time: '4:00 PM', title: 'Pickup', description: 'Air-conditioned transfer from your hotel to the desert meeting point.' },
      { time: '4:45 PM', title: 'Meet your camel', description: 'A short introduction to your camel and handler, plus tips for a comfortable ride.' },
      { time: '5:00 PM', title: 'Sunset trek', description: 'Ride the dune ridge as the sun sets, stopping for photos at the best viewpoints.' },
      { time: '6:00 PM', title: 'Bedouin tea', description: 'Settle in for sweet tea and desert quiet before the return.' },
      { time: '6:45 PM', title: 'Return', description: 'Transfer back to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay'],
      note: 'Pickup around 60–90 minutes before sunset; exact time confirmed the day before.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Is the camel ride suitable for beginners and children?', answer: 'Yes. Camels are led by experienced handlers at walking pace, so no experience is needed. Children aged 3+ ride with a parent or handler nearby.' },
      { question: 'Is riding a camel uncomfortable?', answer: 'The mounting and dismounting is the wobbliest part — your handler guides you through it. Once up, the ride is a gentle sway. Wear comfortable trousers for the best experience.' },
      { question: 'Are the camels well cared for?', answer: 'Yes. We work only with Ababda families who depend on their animals’ health and treat them accordingly. Camels are rested, fed and rotated.' },
      { question: 'How long is the actual ride?', answer: 'Around 45 minutes to an hour on the camel, plus the tea stop and photos — a relaxed pace throughout.' },
      { question: 'Can couples ride together?', answer: 'Camels are ridden individually, but you’ll travel side by side — it’s a favourite for couples and honeymooners at sunset.' },
      { question: 'What should I wear?', answer: 'Long, comfortable trousers, closed shoes and a light jacket for after dark. Sunglasses and a hat help before sunset.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip transfers from Marsa Alam and Port Ghalib are included.' },
      { question: 'Can I add dinner or a quad ride?', answer: 'Yes — our full desert safari combines camel, quad, a Bedouin village and dinner. Just ask to upgrade.' },
      { question: 'Will I see the sunset?', answer: 'That’s the whole idea — the ride is timed so you’re on the ridge as the sun goes down. Cloudy evenings are rare on the Red Sea coast.' },
      { question: 'Is it wheelchair accessible?', answer: 'The desert terrain and camel mounting aren’t wheelchair accessible, but contact us and we’ll suggest the best alternative experience.' },
    ],
    relatedTours: ['marsa-alam-desert-safari', 'quad-bike-marsa-alam'],
    rating: 4.8,
    reviewCount: 288,
    updatedAt: '2026-05-20',
  },
  {
    slug: 'super-safari-jeep-adventure',
    title: 'Super Safari: 4x4 Jeep Adventure & Bedouin Dinner',
    seoTitle: 'Marsa Alam Super Safari | 4x4 Jeep Adventure & Bedouin Dinner',
    metaDescription:
      'A full desert day from Marsa Alam: 4x4 jeep off-roading, a camel ride, quad bike and dinner under the stars. Small groups, licensed guides, hotel pickup.',
    summary: 'The grand desert combo — 4x4 off-roading, quad, camel, Bedouin culture and a starlit dinner in one epic evening.',
    overview: [
      'Our Super Safari is the desert in full: a 4x4 jeep bounding over dunes and dry riverbeds, a quad-bike leg, a sunset camel ride, and an evening of Ababda hospitality with dinner, music and stargazing.',
      'It’s the most complete desert experience we offer, and still comfortably paced for families. Ride shotgun as your driver reads the terrain, then let the night settle in around the campfire.',
    ],
    category: 'desert-safari',
    tags: ['jeep-safari', 'quad-bike', 'camel-ride', 'bedouin', 'dinner', 'stargazing'],
    destinationSlugs: ['wadi-el-gemal'],
    price: { amount: 45, currency: 'EUR', compareAt: 58, unit: 'per person', childAmount: 28 },
    durationHours: 7,
    durationLabel: 'Half day+ (6–7 hrs, afternoon)',
    difficulty: 'Easy',
    groupSize: '2–24 people',
    languages: ['English', 'German', 'Italian', 'Arabic'],
    availability: 'Daily',
    minAge: 3,
    heroImage: img('1520962880247-cfaf541c8724', '4x4 jeep driving over desert dunes on a Marsa Alam super safari', { priority: true }),
    gallery: [
      img('1509316785289-025f5b846b35', 'Quad bikes and jeeps at a desert meeting point near Marsa Alam'),
      img('1547234935-80c7145ec969', 'Camels and jeeps at a Bedouin camp during the super safari'),
      img('1518709268805-4e9042af9f23', 'Bedouin dinner spread with lanterns in the Eastern Desert'),
      img('1470071459604-3b5ec3a7fe05', 'Milky Way over the Marsa Alam desert during a stargazing session'),
    ],
    highlights: [
      '4x4 jeep off-road drive across dunes and wadis',
      'Quad bike leg for the adventurous',
      'Sunset camel ride',
      'Ababda Bedouin village and hospitality',
      'Barbecue dinner, music and stargazing',
    ],
    included: ['Hotel pickup and drop-off', '4x4 jeep drive', 'Quad bike with fuel', 'Camel ride', 'Bedouin village visit', 'Barbecue dinner', 'Licensed guide', 'Water'],
    excluded: ['Gratuities', 'Personal expenses', 'Alcoholic drinks'],
    whatToBring: [...SUN_ESSENTIALS, 'Closed shoes', 'A warm layer for the evening', 'Camera', 'Scarf for dust'],
    itinerary: [
      { time: '2:00 PM', title: 'Pickup', description: 'Air-conditioned transfer from your hotel to the desert base camp.' },
      { time: '3:00 PM', title: 'Jeep off-road', description: 'Climb into the 4x4 for a thrilling drive over dunes and through desert valleys.' },
      { time: '4:00 PM', title: 'Quad ride', description: 'Swap to a quad bike for a guided desert loop.' },
      { time: '5:00 PM', title: 'Bedouin village & camel', description: 'Meet the Ababda, ride a camel, and watch the sunset.' },
      { time: '6:30 PM', title: 'Dinner & stars', description: 'Barbecue dinner, traditional music and a guided look at the night sky.' },
      { time: '9:00 PM', title: 'Return', description: 'Comfortable transfer back to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'El Quseir (surcharge)'],
      note: 'Afternoon pickups confirmed by WhatsApp the day before.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'What’s the difference between this and the standard desert safari?', answer: 'The Super Safari adds a 4x4 jeep off-road drive to the quad, camel, village and dinner — it’s the most complete desert experience we offer and runs a little longer.' },
      { question: 'Is the jeep drive bumpy?', answer: 'It’s an off-road adventure, so expect some fun bumps and dune climbs. Your driver adjusts intensity to the group, and it’s comfortable for families.' },
      { question: 'Can young children join?', answer: 'Yes, children 3+ are welcome. They ride in the jeep and with guides on the quad, and love the camels and campfire.' },
      { question: 'Do I have to do the quad biking?', answer: 'No — every activity is optional. If you’d rather stay in the jeep or relax at camp, that’s completely fine.' },
      { question: 'Is dinner included and are there vegetarian options?', answer: 'Yes, a barbecue dinner is included with vegetarian options always available. Tell us about allergies when you book.' },
      { question: 'How cold does it get at night?', answer: 'The desert cools quickly after sunset, so bring a warm layer even in summer.' },
      { question: 'Are the groups small?', answer: 'We keep groups manageable and split activities so nothing feels crowded. Private departures are available on request.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip air-conditioned transfers from Marsa Alam and Port Ghalib are included.' },
      { question: 'How good is the stargazing?', answer: 'Excellent — the Eastern Desert has very little light pollution. On clear, moonless nights the Milky Way is easily visible.' },
      { question: 'Can we book this as a private tour?', answer: 'Yes. Message us on WhatsApp for private and group rates, ideal for families and special occasions.' },
    ],
    relatedTours: ['marsa-alam-desert-safari', 'quad-bike-marsa-alam', 'camel-ride-marsa-alam'],
    rating: 4.9,
    reviewCount: 356,
    featured: true,
    updatedAt: '2026-06-10',
  },
  {
    slug: 'snorkeling-sataya-dolphin-reef',
    title: 'Sataya Dolphin Reef Snorkeling Trip (Dolphin House)',
    seoTitle: 'Sataya Dolphin Reef Snorkeling Marsa Alam | Swim with Dolphins',
    metaDescription:
      'Snorkel with wild spinner dolphins at Sataya Reef (Dolphin House) from Marsa Alam. Full-day boat trip, pristine coral, lunch and hotel pickup included.',
    summary: 'A full-day boat trip to Sataya Reef to snorkel pristine coral and share the water with wild spinner dolphins.',
    overview: [
      'Sataya Reef — Dolphin House — is the highlight of the southern Red Sea, and this full-day boat trip is the best way to experience it. Cruise out from Hamata across glassy water to a vast horseshoe reef where hundreds of wild spinner dolphins rest and play by day.',
      'You’ll enjoy several snorkel stops over untouched coral gardens, a freshly prepared lunch on board, and — with respect and a little luck — the unforgettable moment of watching wild dolphins glide beneath you. Our guides follow strict responsible-encounter rules so the dolphins stay wild and free.',
    ],
    category: 'snorkeling',
    tags: ['dolphins', 'snorkeling', 'boat-trip', 'sataya', 'coral-reef', 'full-day'],
    destinationSlugs: ['sataya-reef', 'hamata-islands'],
    price: { amount: 55, currency: 'EUR', compareAt: 70, unit: 'per person', childAmount: 35 },
    durationHours: 11,
    durationLabel: 'Full day (10–11 hrs incl. transfer)',
    difficulty: 'Easy',
    groupSize: '1–25 people',
    languages: ['English', 'German', 'Italian'],
    availability: 'Daily (sea conditions permitting)',
    minAge: 4,
    heroImage: img('1607153333879-c174d265f1d2', 'Wild spinner dolphins swimming beneath snorkelers at Sataya Reef near Marsa Alam', { priority: true }),
    gallery: [
      img('1544551763-46a013bb70d5', 'Snorkeler over colourful coral at Sataya Reef'),
      img('1502680390469-be75c86b636f', 'Boat anchored in the turquoise lagoon of Sataya Dolphin Reef'),
      img('1559827260-dc66d52bef19', 'School of tropical fish over Red Sea coral near Marsa Alam'),
      img('1516815231560-8f41ec531527', 'Turquoise shallows of the Hamata region near Sataya'),
    ],
    highlights: [
      'Snorkel near wild spinner dolphins at Sataya',
      'Explore pristine, protected coral gardens',
      'Freshly prepared lunch served on board',
      'Several unhurried snorkel stops',
      'Responsible, small-group encounters',
    ],
    included: ['Hotel pickup and drop-off', 'Boat trip with crew', 'Snorkeling gear (mask, snorkel, fins)', 'Onboard lunch and soft drinks', 'Guide and safety briefing', 'Marine park fees'],
    excluded: ['Underwater camera rental', 'Wetsuit (available in winter)', 'Gratuities', 'Towels'],
    whatToBring: [...SUN_ESSENTIALS, 'Swimwear and towel', 'Motion-sickness tablets if prone', 'Waterproof camera'],
    itinerary: [
      { time: '6:00 AM', title: 'Pickup', description: 'Early transfer south to Hamata harbour (about 2 hours from Marsa Alam).' },
      { time: '8:30 AM', title: 'Set sail', description: 'Board the boat, meet the crew and cruise toward Sataya Reef.' },
      { time: '10:00 AM', title: 'First snorkel & dolphins', description: 'Anchor at the reef for your first snorkel and, conditions permitting, the dolphin encounter.' },
      { time: '12:30 PM', title: 'Lunch on board', description: 'Enjoy a fresh lunch while the crew repositions to a new snorkel spot.' },
      { time: '1:30 PM', title: 'Second snorkel', description: 'More time over the coral gardens and shallows.' },
      { time: '3:00 PM', title: 'Return sail', description: 'Cruise back to harbour with drinks and sun on deck.' },
      { time: '5:30 PM', title: 'Drop-off', description: 'Transfer back to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'Sharm El Luli', 'Hamata hotels'],
      note: 'This is a southern trip with an early start — pickup times of 5:30–6:30 AM are normal and confirmed the day before.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Am I guaranteed to see dolphins?', answer: 'Sataya has a resident pod and sightings are very frequent, but these are wild animals, so we can never guarantee them. We maximise your chances with early timing and experienced skippers, and always follow responsible-encounter rules.' },
      { question: 'Do I need to be a strong swimmer?', answer: 'Basic swimming ability helps, but the lagoon is calm and life jackets and pool noodles are available. Our guides stay close and can assist nervous snorkelers.' },
      { question: 'Is snorkeling equipment provided?', answer: 'Yes — mask, snorkel and fins are included and sanitised. If you prefer your own gear, you’re welcome to bring it.' },
      { question: 'How long is the boat journey to the reef?', answer: 'About 1.5–2 hours each way from Hamata harbour. The southern reefs are worth the distance — they’re far less crowded and beautifully preserved.' },
      { question: 'Will I get seasick?', answer: 'Most people are fine in the usually-calm morning sea. If you’re prone to motion sickness, take a tablet an hour before boarding and stay on deck in the fresh air.' },
      { question: 'Is it suitable for children?', answer: 'Yes, children 4+ love it. Little ones stay in the shallow lagoon with life jackets and a parent, and the crew keeps a careful eye on everyone.' },
      { question: 'Is it responsible / ethical to swim with the dolphins?', answer: 'We think so, when done right. We never chase or feed the dolphins, limit group size and time in the water, and let the animals choose whether to approach — which is why the pod keeps returning.' },
      { question: 'What food is served on board?', answer: 'A freshly prepared buffet-style lunch with vegetarian options, plus soft drinks and water throughout the day. Tell us about allergies in advance.' },
      { question: 'What should I bring?', answer: 'Swimwear, a towel, reef-safe sunscreen, a hat and a waterproof camera. In winter a wetsuit (available to rent) keeps you warm.' },
      { question: 'Does the trip run in winter?', answer: 'Yes, year-round, though sailings depend on sea conditions. Winter water is cooler (around 22°C), so we recommend a wetsuit.' },
      { question: 'Can I dive instead of snorkel at Sataya?', answer: 'This is a snorkeling trip, but certified divers can arrange dives at nearby sites — message us and we’ll tailor it.' },
    ],
    relatedTours: ['hamata-islands-boat-trip', 'abu-dabbab-snorkeling', 'marsa-alam-diving-trip'],
    rating: 4.9,
    reviewCount: 508,
    featured: true,
    bestseller: true,
    updatedAt: '2026-06-12',
  },
  {
    slug: 'abu-dabbab-snorkeling',
    title: 'Abu Dabbab Snorkeling: Swim with Sea Turtles',
    seoTitle: 'Abu Dabbab Snorkeling Marsa Alam | Swim with Sea Turtles & Dugong',
    metaDescription:
      'Snorkel with green sea turtles at Abu Dabbab Bay near Marsa Alam. Calm, shallow water ideal for beginners and families. Easy beach entry, hotel pickup included.',
    summary: 'A relaxed half-day at Abu Dabbab Bay to snorkel with green sea turtles in calm, shallow water — perfect for beginners.',
    overview: [
      'Abu Dabbab is the easiest place on the coast to snorkel with sea turtles. This calm, crescent bay just north of Marsa Alam has a sandy, shallow entry and resident green turtles grazing on the seagrass — no boat, no deep water, no experience required.',
      'It’s the ideal trip for families and first-time snorkelers. Float quietly above the meadows and you may share the bay with a turtle, a guitarfish, or — if the day is kind — the rare and gentle dugong.',
    ],
    category: 'snorkeling',
    tags: ['sea-turtles', 'snorkeling', 'abu-dabbab', 'beginners', 'family-friendly', 'half-day'],
    destinationSlugs: ['abu-dabbab'],
    price: { amount: 30, currency: 'EUR', compareAt: 40, unit: 'per person', childAmount: 18 },
    durationHours: 5,
    durationLabel: 'Half day (4–5 hrs)',
    difficulty: 'Easy',
    groupSize: '1–20 people',
    languages: ['English', 'German', 'Italian'],
    availability: 'Daily',
    minAge: 3,
    heroImage: img('1591025207163-942350e47db2', 'Green sea turtle grazing on seagrass in the shallow bay of Abu Dabbab near Marsa Alam', { priority: true }),
    gallery: [
      img('1544551763-46a013bb70d5', 'Snorkeler exploring the shallow reef at Abu Dabbab Bay'),
      img('1559827260-dc66d52bef19', 'Tropical fish over coral at Abu Dabbab, Marsa Alam'),
      img('1502680390469-be75c86b636f', 'The calm crescent beach of Abu Dabbab Bay'),
    ],
    highlights: [
      'Reliable green sea turtle sightings',
      'Calm, shallow water ideal for beginners',
      'Easy sandy beach entry — no boat needed',
      'Chance to spot guitarfish and the rare dugong',
      'Relaxed pace with a guide on hand',
    ],
    included: ['Hotel pickup and drop-off', 'Snorkeling gear', 'Guide and safety briefing', 'Bottled water', 'Beach access fee'],
    excluded: ['Lunch (beach café available)', 'Sun-lounger rental', 'Gratuities'],
    whatToBring: [...SUN_ESSENTIALS, 'Swimwear and towel', 'Water shoes (optional)', 'Underwater camera'],
    itinerary: [
      { time: '8:30 AM', title: 'Pickup', description: 'Short transfer north to Abu Dabbab Bay (about 30–40 minutes).' },
      { time: '9:15 AM', title: 'Briefing & gear', description: 'Fit your snorkeling gear and get tips on finding the turtles responsibly.' },
      { time: '9:30 AM', title: 'Snorkel with turtles', description: 'Enter from the beach and explore the seagrass meadows and reef edges with your guide.' },
      { time: '11:30 AM', title: 'Free time', description: 'Relax on the beach, swim again, or grab a drink at the café.' },
      { time: '12:30 PM', title: 'Return', description: 'Transfer back to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'Abu Dabbab hotels'],
      note: 'Morning light is best for turtle spotting, so pickups are usually early-to-mid morning.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Will I definitely see turtles at Abu Dabbab?', answer: 'Green turtles live in the bay year-round and sightings are very common, especially in the morning. They’re wild, so nothing is guaranteed, but few guests leave disappointed.' },
      { question: 'Is Abu Dabbab good for beginners?', answer: 'It’s the best beginner spot on the coast — shallow, calm, sandy-bottomed and entered straight from the beach. Life jackets and pool noodles are available.' },
      { question: 'Can I snorkel with turtles without swimming far?', answer: 'Yes. Turtles often graze close to shore in waist-to-chest-deep water, so you rarely need to go far or deep.' },
      { question: 'How close can I get to the turtles?', answer: 'Keep a respectful distance of about 2–3 metres, never touch or chase them, and let them surface to breathe. Your guide shows you how to observe responsibly.' },
      { question: 'Is it suitable for young children?', answer: 'Yes, children 3+ enjoy the shallow bay with a parent and life jacket. It’s one of our most family-friendly trips.' },
      { question: 'Is lunch included?', answer: 'Lunch isn’t included, but there’s a beach café on site for snacks and drinks. You’re welcome to bring your own too.' },
      { question: 'Do I need water shoes?', answer: 'They’re optional but handy for the sandy-and-seagrass entry. Reef-safe footwear also protects the seagrass and your feet.' },
      { question: 'What else might I see?', answer: 'Beyond turtles, look for guitarfish, rays, colourful reef fish and — rarely — a dugong grazing the meadows.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip transfers from Marsa Alam and Port Ghalib are included.' },
      { question: 'Can I combine Abu Dabbab with another activity?', answer: 'Yes — it pairs well with a desert safari on another day, or ask about a combined snorkel-and-safari package.' },
    ],
    relatedTours: ['snorkeling-sataya-dolphin-reef', 'hamata-islands-boat-trip', 'marsa-alam-desert-safari'],
    rating: 4.8,
    reviewCount: 374,
    featured: true,
    updatedAt: '2026-05-28',
  },
  {
    slug: 'hamata-islands-boat-trip',
    title: 'Hamata Islands Boat Trip (Qulaan Mangroves)',
    seoTitle: 'Hamata Islands Boat Trip | Qulaan Mangroves, Marsa Alam',
    metaDescription:
      'Cruise the protected Hamata (Qulaan) Islands from Marsa Alam — mangrove lagoons, empty sandbars and pristine coral. Full-day boat trip with lunch and hotel pickup.',
    summary: 'A full-day cruise through the protected Hamata archipelago — mangrove lagoons, white sandbars and untouched reefs.',
    overview: [
      'Far south of the crowds, the Hamata (Qulaan) Islands are the Red Sea at its most pristine. This full-day boat trip drifts between mangrove-fringed sandbars and coral gardens inside a protected marine park, with water so clear and shallow it glows turquoise from the boat.',
      'Snorkel over healthy reefs, wade onto empty white sandbars, and watch ospreys and herons work the mangroves. It’s a longer journey south — and the reward is a corner of Egypt that still feels wild.',
    ],
    category: 'boat-trips',
    tags: ['boat-trip', 'hamata', 'mangroves', 'snorkeling', 'islands', 'full-day', 'nature'],
    destinationSlugs: ['hamata-islands', 'sataya-reef'],
    price: { amount: 50, currency: 'EUR', compareAt: 65, unit: 'per person', childAmount: 32 },
    durationHours: 10,
    durationLabel: 'Full day (9–10 hrs incl. transfer)',
    difficulty: 'Easy',
    groupSize: '1–25 people',
    languages: ['English', 'German', 'Italian'],
    availability: 'Several times per week (sea conditions permitting)',
    minAge: 4,
    heroImage: img('1516815231560-8f41ec531527', 'Turquoise shallows and mangrove sandbars of the Hamata Islands south of Marsa Alam', { priority: true }),
    gallery: [
      img('1502680390469-be75c86b636f', 'Boat anchored over clear water near the Qulaan mangroves'),
      img('1544551763-46a013bb70d5', 'Snorkeler over healthy coral in the Hamata marine park'),
      img('1559827260-dc66d52bef19', 'Reef fish in the shallow gardens of the Hamata Islands'),
    ],
    highlights: [
      'Explore a protected marine park and mangrove islands',
      'Snorkel pristine, uncrowded coral gardens',
      'Relax on empty white sandbars',
      'Rich birdlife including ospreys and herons',
      'Onboard lunch and unhurried stops',
    ],
    included: ['Hotel pickup and drop-off', 'Boat trip with crew', 'Snorkeling gear', 'Onboard lunch and soft drinks', 'Guide', 'Marine park fees'],
    excluded: ['Wetsuit rental (winter)', 'Gratuities', 'Towels'],
    whatToBring: [...SUN_ESSENTIALS, 'Swimwear and towel', 'Waterproof camera', 'Motion-sickness tablets if prone'],
    itinerary: [
      { time: '6:30 AM', title: 'Pickup', description: 'Transfer south to Hamata harbour (around 2 hours).' },
      { time: '8:30 AM', title: 'Set sail', description: 'Board and cruise into the protected archipelago.' },
      { time: '10:00 AM', title: 'First snorkel', description: 'Anchor at a coral garden for snorkeling with your guide.' },
      { time: '12:00 PM', title: 'Sandbar & lunch', description: 'Stop at a mangrove sandbar for lunch and beach time.' },
      { time: '1:30 PM', title: 'Second snorkel', description: 'One more reef stop before the return sail.' },
      { time: '3:00 PM', title: 'Return', description: 'Cruise back and transfer to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Sharm El Luli', 'Hamata hotels'],
      note: 'Southern trip with an early start; times confirmed the day before.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'How is Hamata different from other boat trips?', answer: 'Hamata sits inside a protected marine park far to the south, so the reefs are healthier and the islands almost empty. It’s quieter and more nature-focused than northern trips.' },
      { question: 'Can I see dolphins on this trip?', answer: 'Sataya Reef is in the same region, and some Hamata itineraries pass nearby — ask us about a combined dolphin-and-islands option.' },
      { question: 'Is there a lot of walking or hiking?', answer: 'No. The sandbars are flat and small; you simply wade ashore. It’s relaxed throughout.' },
      { question: 'Is snorkeling gear included?', answer: 'Yes — mask, snorkel and fins are provided and sanitised. Bring your own if you prefer.' },
      { question: 'How long is the drive to the harbour?', answer: 'About 2 hours each way from Marsa Alam, which is why the day starts early. The remoteness is exactly what keeps Hamata pristine.' },
      { question: 'Is it suitable for children and non-swimmers?', answer: 'Yes. The shallow, calm lagoons and sandbars are family-friendly, and life jackets are available for non-swimmers.' },
      { question: 'What about seasickness?', answer: 'The southern sea is usually calm in the morning. If you’re prone to motion sickness, take a tablet before boarding and stay on deck.' },
      { question: 'Is lunch provided?', answer: 'Yes, a fresh lunch is served on board or on the sandbar, with vegetarian options and soft drinks included.' },
      { question: 'Can I visit the mangroves?', answer: 'Yes — the Qulaan mangroves are a highlight. We view them responsibly from the boat and sandbars to protect the fragile ecosystem.' },
      { question: 'Does the trip run all year?', answer: 'It runs several times a week year-round, weather permitting. Winter water is cooler, so a wetsuit is recommended.' },
    ],
    relatedTours: ['snorkeling-sataya-dolphin-reef', 'abu-dabbab-snorkeling'],
    rating: 4.8,
    reviewCount: 214,
    updatedAt: '2026-05-30',
  },
  {
    slug: 'marsa-alam-diving-trip',
    title: 'Marsa Alam Diving Trip: Guided Reef & Elphinstone',
    seoTitle: 'Marsa Alam Diving Trip | Guided Reef Dives & Elphinstone | PADI',
    metaDescription:
      'Dive Marsa Alam’s world-class reefs with PADI guides. Two guided boat dives, small groups, full equipment and hotel pickup. Try-dives for beginners available.',
    summary: 'Two guided boat dives on Marsa Alam’s spectacular reefs, with PADI pros, small groups and full equipment.',
    overview: [
      'Marsa Alam is one of the Red Sea’s premier dive destinations, and this two-dive boat trip puts you on its best reefs with a PADI-certified guide. Drift along coral walls alive with anthias and butterflyfish, hover over gardens of hard and soft coral, and keep an eye on the blue for turtles, reef sharks and — at Elphinstone — the chance of an oceanic encounter.',
      'Certified divers can log two guided dives; beginners can arrange a supervised try-dive. Groups are small, safety is meticulous, and the underwater world here rarely disappoints.',
    ],
    category: 'diving',
    tags: ['diving', 'scuba', 'padi', 'elphinstone', 'reef', 'boat-trip'],
    destinationSlugs: ['sataya-reef', 'abu-dabbab'],
    price: { amount: 75, currency: 'EUR', compareAt: 95, unit: 'per person' },
    durationHours: 8,
    durationLabel: 'Full day (7–8 hrs, 2 dives)',
    difficulty: 'Moderate',
    groupSize: '1–8 divers per guide',
    languages: ['English', 'German', 'Italian'],
    availability: 'Daily (sea conditions permitting)',
    minAge: 10,
    heroImage: img('1682687220208-22d7a2543e88', 'Scuba diver exploring a vibrant coral wall on a Marsa Alam diving trip', { priority: true }),
    gallery: [
      img('1544551763-46a013bb70d5', 'Diver over a Red Sea coral garden near Marsa Alam'),
      img('1559827260-dc66d52bef19', 'School of tropical fish around a Marsa Alam reef'),
      img('1502680390469-be75c86b636f', 'Dive boat anchored over a Marsa Alam reef'),
    ],
    highlights: [
      'Two guided boat dives on top Marsa Alam reefs',
      'PADI-certified guides and small groups',
      'Full rental equipment included',
      'Chance of turtles, reef sharks and Elphinstone drop-offs',
      'Try-dive option for beginners',
    ],
    included: ['Hotel pickup and drop-off', 'Two guided boat dives', 'Full dive equipment', 'Tanks and weights', 'PADI dive guide', 'Onboard lunch and drinks', 'Marine park fees'],
    excluded: ['Dive insurance', 'Nitrox (on request)', 'Underwater camera rental', 'Gratuities', 'Certification course fees'],
    whatToBring: [...SUN_ESSENTIALS, 'Dive certification card and logbook', 'Swimwear and towel', 'Any personal dive computer'],
    itinerary: [
      { time: '7:00 AM', title: 'Pickup', description: 'Transfer to the dive centre and harbour.' },
      { time: '8:00 AM', title: 'Briefing & gear', description: 'Check certification, fit equipment and receive the dive-site briefing.' },
      { time: '9:30 AM', title: 'First dive', description: 'Guided descent on a coral reef or wall, tailored to your certification level.' },
      { time: '11:30 AM', title: 'Surface interval & lunch', description: 'Relax on board with lunch and refreshments between dives.' },
      { time: '1:00 PM', title: 'Second dive', description: 'A second guided dive at a complementary site.' },
      { time: '3:00 PM', title: 'Return', description: 'Cruise back and transfer to your hotel.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'Abu Dabbab hotels'],
      note: 'No flying within 18–24 hours after diving — plan your departure accordingly.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'Do I need to be a certified diver?', answer: 'For the two guided dives, yes — bring your certification card and logbook. Beginners can arrange a supervised try-dive (Discover Scuba) instead; just let us know when booking.' },
      { question: 'Which reefs will we dive?', answer: 'Sites are chosen on the day for conditions and your level, and may include Marsa Alam house reefs, Abu Dabbab, Sha’ab Samadai or, for experienced divers, Elphinstone. Your guide confirms the plan at the briefing.' },
      { question: 'Can I dive Elphinstone?', answer: 'Elphinstone is an advanced site with currents and depth, suitable for experienced, Advanced-certified divers. We’ll assess conditions and your experience before including it.' },
      { question: 'Is equipment included?', answer: 'Yes, full rental equipment, tanks and weights are included. Bring your own computer, mask or wetsuit if you prefer.' },
      { question: 'What marine life might I see?', answer: 'Expect vibrant coral, anthias, groupers, moray eels and turtles. Reef sharks, dolphins and — at Elphinstone — oceanic whitetips are seasonal possibilities.' },
      { question: 'Do I need dive insurance?', answer: 'Dive-specific insurance (e.g. DAN) is strongly recommended and required for some sites. It’s not included, but we can point you to providers.' },
      { question: 'When can I fly after diving?', answer: 'Follow the standard guidance: wait at least 18 hours after a single dive and 24 hours after multiple dives before flying.' },
      { question: 'Is nitrox available?', answer: 'Yes, nitrox is available on request for certified enriched-air divers at a small extra charge.' },
      { question: 'How small are the groups?', answer: 'We keep a maximum of about 8 divers per guide, often fewer, so you get attentive supervision and a relaxed pace.' },
      { question: 'Can beginners really dive here?', answer: 'Yes — Marsa Alam’s calm, clear house reefs are ideal for first-timers. A try-dive with a certified instructor is a safe, guided introduction.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip transfers from Marsa Alam and Port Ghalib are included.' },
    ],
    relatedTours: ['snorkeling-sataya-dolphin-reef', 'abu-dabbab-snorkeling', 'hamata-islands-boat-trip'],
    rating: 4.9,
    reviewCount: 197,
    updatedAt: '2026-06-08',
  },
  {
    slug: 'luxor-day-trip',
    title: 'Luxor Day Trip from Marsa Alam: Valley of the Kings',
    seoTitle: 'Luxor Day Trip from Marsa Alam | Valley of the Kings & Karnak',
    metaDescription:
      'Visit Luxor from Marsa Alam on a guided day trip: Valley of the Kings, Karnak Temple and the Colossi of Memnon. Egyptologist guide, lunch and hotel pickup.',
    summary: 'A full-day journey to Luxor — the Valley of the Kings, Karnak and Hatshepsut — with an expert Egyptologist guide.',
    overview: [
      'Stand where the pharaohs were laid to rest. This full-day trip from Marsa Alam takes you across the desert to Luxor, the world’s greatest open-air museum, with a private Egyptologist guide to bring 3,000 years of history to life.',
      'You’ll descend into the painted tombs of the Valley of the Kings, walk the colossal colonnades of Karnak, admire the terraces of Hatshepsut’s temple and pause at the Colossi of Memnon. Air-conditioned transfers and lunch keep the long day comfortable.',
    ],
    category: 'day-trips',
    tags: ['luxor', 'day-trip', 'culture', 'history', 'egyptology', 'temples'],
    destinationSlugs: [],
    price: { amount: 65, currency: 'EUR', compareAt: 85, unit: 'per person', childAmount: 40 },
    durationHours: 14,
    durationLabel: 'Full day (13–14 hrs)',
    difficulty: 'Moderate',
    groupSize: '1–15 people',
    languages: ['English', 'German', 'Italian', 'French'],
    availability: 'Several times per week',
    minAge: 5,
    heroImage: img('1539768942893-daf53e448371', 'Ancient hieroglyph-carved columns at Karnak Temple in Luxor', { priority: true }),
    gallery: [
      img('1568322445389-f64ac2515020', 'Statues and temple architecture in Luxor, Egypt'),
      img('1553913861-c0fddf2619ee', 'The Colossi of Memnon on the west bank of Luxor'),
      img('1590133324192-7b7c6d6b7b8f', 'Painted tomb interior in the Valley of the Kings'),
    ],
    highlights: [
      'Explore the tombs of the Valley of the Kings',
      'Marvel at the great hypostyle hall of Karnak Temple',
      'Visit the terraced Temple of Hatshepsut',
      'Photograph the Colossi of Memnon',
      'Private, licensed Egyptologist guide',
    ],
    included: ['Air-conditioned hotel pickup and drop-off', 'Egyptologist guide', 'All entrance fees to listed sites', 'Lunch at a local restaurant', 'Bottled water', 'Convoy transfer to Luxor'],
    excluded: ['Optional sites (e.g. Nefertari’s tomb, hot-air balloon)', 'Gratuities', 'Drinks with lunch', 'Personal expenses'],
    whatToBring: [...SUN_ESSENTIALS, 'Comfortable walking shoes', 'Passport or ID', 'Cash for optional extras and tips', 'Modest clothing for temples'],
    itinerary: [
      { time: '4:00 AM', title: 'Early pickup', description: 'Very early air-conditioned transfer across the desert to Luxor (about 4 hours).' },
      { time: '8:30 AM', title: 'Valley of the Kings', description: 'Descend into the royal tombs with your Egyptologist guide.' },
      { time: '10:30 AM', title: 'Hatshepsut & Memnon', description: 'Visit the temple of Hatshepsut and the Colossi of Memnon.' },
      { time: '1:00 PM', title: 'Lunch', description: 'Enjoy lunch at a local restaurant with Nile views.' },
      { time: '2:30 PM', title: 'Karnak Temple', description: 'Explore the vast temple complex and hypostyle hall of Karnak.' },
      { time: '4:00 PM', title: 'Return', description: 'Transfer back to Marsa Alam, arriving in the evening.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'El Quseir'],
      note: 'This is a very early start due to the distance. Bring your passport/ID for the road checkpoints.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'How long is the drive to Luxor?', answer: 'About 4 hours each way from Marsa Alam. It’s an early start, but the sites are extraordinary and the vehicle is air-conditioned and comfortable.' },
      { question: 'Is the guide a real Egyptologist?', answer: 'Yes. Your guide is a licensed, English-speaking Egyptologist (other languages on request) who brings the history to life far beyond a guidebook.' },
      { question: 'Which sites are included?', answer: 'The standard itinerary covers the Valley of the Kings, Temple of Hatshepsut, Colossi of Memnon and Karnak Temple. Some special tombs (like Tutankhamun’s or Nefertari’s) carry an optional extra fee.' },
      { question: 'Is this trip suitable for children?', answer: 'Yes, children 5+ manage well, though the long drive and heat mean it suits older kids best. We keep the pace comfortable and build in rest and lunch.' },
      { question: 'What should I wear?', answer: 'Light, modest clothing that covers shoulders and knees for the temples, comfortable walking shoes, a hat and sunglasses. It gets hot, especially midday.' },
      { question: 'Do I need my passport?', answer: 'Bring your passport or a copy/ID — there are police checkpoints on the desert road between the coast and the Nile Valley.' },
      { question: 'Is lunch included?', answer: 'Yes, lunch at a local restaurant is included. Drinks are usually extra. Tell us about dietary needs in advance.' },
      { question: 'Can I do a hot-air balloon over Luxor?', answer: 'A sunrise balloon is possible as an add-on, but it requires an overnight stay in Luxor due to timing. Ask us about a two-day option.' },
      { question: 'How much walking is involved?', answer: 'A fair amount, across uneven ground and tomb steps, mostly in heat. Good shoes and water make it easy; tell us about mobility needs and we’ll advise.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip air-conditioned transfers from Marsa Alam and Port Ghalib are included.' },
      { question: 'Is it better to visit Luxor or Aswan from Marsa Alam?', answer: 'Luxor is closer and richer in New Kingdom temples and tombs; Aswan offers Nile scenery, Philae and the High Dam. If you can, do both on separate days — we run both trips.' },
    ],
    relatedTours: ['aswan-day-trip', 'marsa-alam-desert-safari'],
    rating: 4.8,
    reviewCount: 331,
    featured: true,
    updatedAt: '2026-06-15',
  },
  {
    slug: 'aswan-day-trip',
    title: 'Aswan Day Trip from Marsa Alam: Philae & High Dam',
    seoTitle: 'Aswan Day Trip from Marsa Alam | Philae Temple & High Dam',
    metaDescription:
      'Discover Aswan from Marsa Alam on a guided full-day trip: Philae Temple, the High Dam and a Nile felucca sail. Egyptologist guide, lunch and hotel pickup included.',
    summary: 'A full-day trip to Aswan — Philae Temple, the High Dam and a felucca sail on the Nile — with an Egyptologist guide.',
    overview: [
      'Aswan is Egypt at its most serene: the Nile widening between granite islands, feluccas leaning into the breeze, and the exquisite temple of Philae rising from the water. This full-day trip from Marsa Alam brings it all within reach, with a private Egyptologist guide.',
      'Visit the island temple of Philae, learn how the High Dam reshaped modern Egypt, and sail the Nile aboard a traditional felucca. It’s a gentler, more scenic counterpart to the Luxor trip — and just as memorable.',
    ],
    category: 'day-trips',
    tags: ['aswan', 'day-trip', 'culture', 'nile', 'philae', 'felucca'],
    destinationSlugs: [],
    price: { amount: 70, currency: 'EUR', compareAt: 90, unit: 'per person', childAmount: 42 },
    durationHours: 14,
    durationLabel: 'Full day (13–14 hrs)',
    difficulty: 'Moderate',
    groupSize: '1–15 people',
    languages: ['English', 'German', 'Italian', 'French'],
    availability: 'Several times per week',
    minAge: 5,
    heroImage: img('1585506942812-e72b29cef752', 'Philae Temple rising from the Nile near Aswan, Egypt', { priority: true }),
    gallery: [
      img('1568322445389-f64ac2515020', 'Feluccas sailing on the Nile at Aswan'),
      img('1539768942893-daf53e448371', 'Ancient temple carvings at Philae near Aswan'),
      img('1553913861-c0fddf2619ee', 'Granite landscape and the Nile around Aswan'),
    ],
    highlights: [
      'Visit the island Temple of Philae by motorboat',
      'See the engineering marvel of the Aswan High Dam',
      'Sail the Nile aboard a traditional felucca',
      'Private, licensed Egyptologist guide',
      'Scenic Nile Valley landscapes',
    ],
    included: ['Air-conditioned hotel pickup and drop-off', 'Egyptologist guide', 'Entrance fees to listed sites', 'Motorboat to Philae', 'Felucca sail', 'Lunch', 'Bottled water'],
    excluded: ['Optional Abu Simbel extension', 'Gratuities', 'Drinks with lunch', 'Personal expenses'],
    whatToBring: [...SUN_ESSENTIALS, 'Comfortable walking shoes', 'Passport or ID', 'Cash for tips and extras', 'Modest clothing for the temple'],
    itinerary: [
      { time: '3:30 AM', title: 'Early pickup', description: 'Air-conditioned transfer across the desert to Aswan (about 5 hours).' },
      { time: '9:00 AM', title: 'Philae Temple', description: 'Take a short motorboat ride to the island temple of Isis with your guide.' },
      { time: '11:00 AM', title: 'High Dam', description: 'Visit the Aswan High Dam and learn its role in modern Egypt.' },
      { time: '12:30 PM', title: 'Lunch & felucca', description: 'Enjoy lunch, then sail the Nile on a traditional felucca.' },
      { time: '2:30 PM', title: 'Return', description: 'Transfer back to Marsa Alam, arriving in the evening.' },
    ],
    pickup: {
      included: true,
      areas: ['Marsa Alam town', 'Port Ghalib', 'Coraya Bay', 'El Quseir'],
      note: 'Aswan is farther than Luxor, so expect a very early start and a long but scenic day.',
    },
    cancellation: STANDARD_CANCELLATION,
    faqs: [
      { question: 'How far is Aswan from Marsa Alam?', answer: 'Around 5 hours each way by road. It’s a long day with an early start, but the temples, the dam and the felucca sail make it worthwhile.' },
      { question: 'What makes Aswan different from Luxor?', answer: 'Aswan is more about Nile scenery, the graceful Philae temple and a felucca sail, while Luxor focuses on the tombs and vast temples of the New Kingdom. Both are superb; many guests do each on a separate day.' },
      { question: 'Can I add Abu Simbel?', answer: 'Abu Simbel is a further 3 hours south of Aswan, so it usually requires an overnight or a very long two-day itinerary. Ask us and we’ll design it for you.' },
      { question: 'Is the felucca sail included?', answer: 'Yes, a traditional felucca sail on the Nile is part of the standard itinerary — a relaxing highlight of the day.' },
      { question: 'Is there a lot of walking?', answer: 'Moderate walking at Philae and the dam, on mostly even ground. Good shoes, a hat and water keep it comfortable.' },
      { question: 'Do I need my passport?', answer: 'Yes, bring your passport or ID for the checkpoints along the desert road.' },
      { question: 'Is it suitable for children?', answer: 'Children 5+ can join, though the long drive suits older kids best. The boat rides are usually a hit.' },
      { question: 'What should I wear?', answer: 'Light, modest clothing for the temple, comfortable shoes, a hat and sunglasses. Aswan can be very warm midday.' },
      { question: 'Is lunch included?', answer: 'Yes, lunch is included; drinks are usually extra. Let us know about dietary requirements when booking.' },
      { question: 'Is hotel pickup included?', answer: 'Yes, round-trip air-conditioned transfers from Marsa Alam and Port Ghalib are included.' },
    ],
    relatedTours: ['luxor-day-trip', 'marsa-alam-desert-safari'],
    rating: 4.8,
    reviewCount: 176,
    updatedAt: '2026-06-14',
  },
];

export const tourBySlug = new Map(tours.map((t) => [t.slug, t]));

export function getTour(slug: string): Tour | undefined {
  return tourBySlug.get(slug);
}

export function getToursByCategory(category: string): Tour[] {
  return tours.filter((t) => t.category === category);
}

export function getToursByDestination(destinationSlug: string): Tour[] {
  return tours.filter((t) => t.destinationSlugs.includes(destinationSlug));
}

export function getFeaturedTours(): Tour[] {
  return tours.filter((t) => t.featured);
}

export function getBestsellerTours(): Tour[] {
  return tours.filter((t) => t.bestseller);
}

/** Resolve related tours, falling back to same-category if none specified. */
export function getRelatedTours(tour: Tour, limit = 3): Tour[] {
  const explicit = tour.relatedTours.map((s) => tourBySlug.get(s)).filter((t): t is Tour => Boolean(t));
  if (explicit.length >= limit) return explicit.slice(0, limit);
  const fallback = tours.filter(
    (t) => t.slug !== tour.slug && t.category === tour.category && !tour.relatedTours.includes(t.slug),
  );
  return [...explicit, ...fallback].slice(0, limit);
}
